// Generated by scripts/generate-image-registry.mjs — do not edit by hand.
//
// Importing images as modules puts them through the Next.js asset pipeline, so
// each file is emitted with a content hash in its name. Replacing a picture
// changes its URL automatically, which is what stops browsers serving a stale
// copy — the problem manual filenames in public/ kept causing.
//
// Keys are the original public paths, so existing "/assets/..." strings in data
// and components keep working: SiteImage resolves them through this map.

import type { StaticImageData } from "next/image";

import ahmed_saudee from "./ahmed-saudee.webp";
import brands_castoldi_transparent from "./brands/castoldi-transparent.webp";
import brands_castoldi from "./brands/castoldi.webp";
import brands_castrol_transparent from "./brands/castrol-transparent.webp";
import brands_castrol from "./brands/castrol.webp";
import brands_donaldson_transparent from "./brands/donaldson-transparent.webp";
import brands_donaldson from "./brands/donaldson.webp";
import brands_kashavaru from "./brands/kashavaru.webp";
import brands_marol_transparent from "./brands/marol-transparent.webp";
import brands_marol from "./brands/marol.webp";
import brands_multiflex_transparent from "./brands/multiflex-transparent.webp";
import brands_nakashima_transparent from "./brands/nakashima-transparent.webp";
import brands_nakashima from "./brands/nakashima.webp";
import brands_ppg_transparent from "./brands/ppg-transparent.webp";
import brands_ppg from "./brands/ppg.webp";
import brands_raywin_transparent from "./brands/raywin-transparent.webp";
import brands_suzuki_transparent from "./brands/suzuki-transparent.webp";
import brands_suzuki from "./brands/suzuki.webp";
import brands_yanmar_transparent from "./brands/yanmar-transparent.webp";
import brands_yanmar from "./brands/yanmar.webp";
import bridge from "./bridge.webp";
import business_hero_1 from "./business-hero-1.webp";
import business_hero_2 from "./business-hero-2.webp";
import business_hero_3 from "./business-hero-3.webp";
import business_tab_hero from "./business-tab-hero.webp";
import business_tab_landscape from "./business-tab-landscape.webp";
import contact_site from "./contact-site.webp";
import conventional_ferry from "./conventional-ferry.webp";
import corporate_hero from "./corporate-hero.webp";
import dredging from "./dredging.webp";
import fleet_showcase1 from "./fleet-showcase1.webp";
import fleet_showcase2 from "./fleet-showcase2.webp";
import fleet_showcase3 from "./fleet-showcase3.webp";
import fleet_showcase4 from "./fleet-showcase4.webp";
import hero_background from "./hero-background.webp";
import infrastructure from "./infrastructure.webp";
import investments_eco_resort from "./investments/eco-resort.webp";
import investments_economic_hub_poster from "./investments/economic-hub-poster.webp";
import investments_racing_circuit from "./investments/racing-circuit.webp";
import investments_ship_repair from "./investments/ship-repair.webp";
import investments_staff_housing from "./investments/staff-housing.webp";
import investments_tourism_hospitality from "./investments/tourism-hospitality.webp";
import investments_transshipment_port from "./investments/transshipment-port.webp";
import leadership_01 from "./leadership/01.webp";
import leadership_02 from "./leadership/02.webp";
import leadership_03 from "./leadership/03.webp";
import leadership_04 from "./leadership/04.webp";
import leadership_05 from "./leadership/05.webp";
import leadership_06 from "./leadership/06.webp";
import leadership_07 from "./leadership/07.webp";
import leadership_08 from "./leadership/08.webp";
import leadership_09 from "./leadership/09.webp";
import leadership_10 from "./leadership/10.webp";
import leadership_11 from "./leadership/11.webp";
import leadership_12 from "./leadership/12.webp";
import leadership_13 from "./leadership/13.webp";
import leadership_14 from "./leadership/14.webp";
import leadership_15 from "./leadership/15.webp";
import leadership_16 from "./leadership/16.webp";
import leadership_17 from "./leadership/17.webp";
import leadership_18 from "./leadership/18.webp";
import leadership_19 from "./leadership/19.webp";
import leadership_20 from "./leadership/20.webp";
import leadership_21 from "./leadership/21.webp";
import leadership_22 from "./leadership/22.webp";
import leadership_23 from "./leadership/23.webp";
import leadership_24 from "./leadership/24.webp";
import leadership_25 from "./leadership/25.webp";
import leadership_26 from "./leadership/26.webp";
import leadership_27 from "./leadership/27.webp";
import leadership_28 from "./leadership/28.webp";
import leadership_29 from "./leadership/29.webp";
import maldives_atolls_light from "./maldives-atolls-light.svg";
import male_taxi_fleet from "./male-taxi-fleet.webp";
import milestones_1981 from "./milestones/1981.webp";
import milestones_2003 from "./milestones/2003.webp";
import milestones_2008 from "./milestones/2008.webp";
import milestones_2015 from "./milestones/2015.webp";
import milestones_2019 from "./milestones/2019.webp";
import milestones_2020 from "./milestones/2020.webp";
import milestones_2024 from "./milestones/2024.webp";
import milestones_2025 from "./milestones/2025.webp";
import milestones_company_construction_and_dredging from "./milestones/company-construction-and-dredging.webp";
import milestones_company1 from "./milestones/company1.webp";
import milestones_company2 from "./milestones/company2.webp";
import milestones_construction_and_dredging_public_transport from "./milestones/construction-and-dredging-public-transport.webp";
import milestones_construction_and_dredging1 from "./milestones/construction-and-dredging1.webp";
import milestones_construction_and_dredging2 from "./milestones/construction-and-dredging2.webp";
import milestones_construction_and_dredging3 from "./milestones/construction-and-dredging3.webp";
import milestones_construction_and_dredging4 from "./milestones/construction-and-dredging4.webp";
import milestones_corporate_hero from "./milestones/corporate-hero.webp";
import milestones_dredging from "./milestones/dredging.webp";
import milestones_public_transport1 from "./milestones/public-transport1.webp";
import milestones_public_transport2 from "./milestones/public-transport2.webp";
import milestones_public_transport3 from "./milestones/public-transport3.webp";
import milestones_public_transport4 from "./milestones/public-transport4.webp";
import milestones_team_engineering from "./milestones/team-engineering.webp";
import milestones_trading_and_engineering1 from "./milestones/trading-and-engineering1.webp";
import milestones_trading_and_engineering2 from "./milestones/trading-and-engineering2.webp";
import milestones_trading_and_engineering3 from "./milestones/trading-and-engineering3.webp";
import milestones_trading_and_engineering4 from "./milestones/trading-and-engineering4.webp";
import milestones_trading_and_engineering5 from "./milestones/trading-and-engineering5.webp";
import milestones_transport1 from "./milestones/transport1.webp";
import mission_scene from "./mission-scene.webp";
import mtcc_logo from "./mtcc-logo.png";
import mtcc_vendor_qr from "./mtcc-vendor-qr.svg";
import mtcc_waves from "./mtcc-waves.svg";
import product_image from "./product-image.webp";
import section_photo from "./section-photo.webp";
import shipbuilding from "./shipbuilding.webp";
import team_engineering from "./team-engineering.webp";
import team_welding from "./team-welding.webp";
import transport from "./transport.webp";
import vision_scene from "./vision-scene.webp";

export const imageRegistry: Record<string, StaticImageData> = {
  "/assets/ahmed-saudee.webp": ahmed_saudee,
  "/assets/brands/castoldi-transparent.webp": brands_castoldi_transparent,
  "/assets/brands/castoldi.webp": brands_castoldi,
  "/assets/brands/castrol-transparent.webp": brands_castrol_transparent,
  "/assets/brands/castrol.webp": brands_castrol,
  "/assets/brands/donaldson-transparent.webp": brands_donaldson_transparent,
  "/assets/brands/donaldson.webp": brands_donaldson,
  "/assets/brands/kashavaru.webp": brands_kashavaru,
  "/assets/brands/marol-transparent.webp": brands_marol_transparent,
  "/assets/brands/marol.webp": brands_marol,
  "/assets/brands/multiflex-transparent.webp": brands_multiflex_transparent,
  "/assets/brands/nakashima-transparent.webp": brands_nakashima_transparent,
  "/assets/brands/nakashima.webp": brands_nakashima,
  "/assets/brands/ppg-transparent.webp": brands_ppg_transparent,
  "/assets/brands/ppg.webp": brands_ppg,
  "/assets/brands/raywin-transparent.webp": brands_raywin_transparent,
  "/assets/brands/suzuki-transparent.webp": brands_suzuki_transparent,
  "/assets/brands/suzuki.webp": brands_suzuki,
  "/assets/brands/yanmar-transparent.webp": brands_yanmar_transparent,
  "/assets/brands/yanmar.webp": brands_yanmar,
  "/assets/bridge.webp": bridge,
  "/assets/business-hero-1.webp": business_hero_1,
  "/assets/business-hero-2.webp": business_hero_2,
  "/assets/business-hero-3.webp": business_hero_3,
  "/assets/business-tab-hero.webp": business_tab_hero,
  "/assets/business-tab-landscape.webp": business_tab_landscape,
  "/assets/contact-site.webp": contact_site,
  "/assets/conventional-ferry.webp": conventional_ferry,
  "/assets/corporate-hero.webp": corporate_hero,
  "/assets/dredging.webp": dredging,
  "/assets/fleet-showcase1.webp": fleet_showcase1,
  "/assets/fleet-showcase2.webp": fleet_showcase2,
  "/assets/fleet-showcase3.webp": fleet_showcase3,
  "/assets/fleet-showcase4.webp": fleet_showcase4,
  "/assets/hero-background.webp": hero_background,
  "/assets/infrastructure.webp": infrastructure,
  "/assets/investments/eco-resort.webp": investments_eco_resort,
  "/assets/investments/economic-hub-poster.webp": investments_economic_hub_poster,
  "/assets/investments/racing-circuit.webp": investments_racing_circuit,
  "/assets/investments/ship-repair.webp": investments_ship_repair,
  "/assets/investments/staff-housing.webp": investments_staff_housing,
  "/assets/investments/tourism-hospitality.webp": investments_tourism_hospitality,
  "/assets/investments/transshipment-port.webp": investments_transshipment_port,
  "/assets/leadership/01.webp": leadership_01,
  "/assets/leadership/02.webp": leadership_02,
  "/assets/leadership/03.webp": leadership_03,
  "/assets/leadership/04.webp": leadership_04,
  "/assets/leadership/05.webp": leadership_05,
  "/assets/leadership/06.webp": leadership_06,
  "/assets/leadership/07.webp": leadership_07,
  "/assets/leadership/08.webp": leadership_08,
  "/assets/leadership/09.webp": leadership_09,
  "/assets/leadership/10.webp": leadership_10,
  "/assets/leadership/11.webp": leadership_11,
  "/assets/leadership/12.webp": leadership_12,
  "/assets/leadership/13.webp": leadership_13,
  "/assets/leadership/14.webp": leadership_14,
  "/assets/leadership/15.webp": leadership_15,
  "/assets/leadership/16.webp": leadership_16,
  "/assets/leadership/17.webp": leadership_17,
  "/assets/leadership/18.webp": leadership_18,
  "/assets/leadership/19.webp": leadership_19,
  "/assets/leadership/20.webp": leadership_20,
  "/assets/leadership/21.webp": leadership_21,
  "/assets/leadership/22.webp": leadership_22,
  "/assets/leadership/23.webp": leadership_23,
  "/assets/leadership/24.webp": leadership_24,
  "/assets/leadership/25.webp": leadership_25,
  "/assets/leadership/26.webp": leadership_26,
  "/assets/leadership/27.webp": leadership_27,
  "/assets/leadership/28.webp": leadership_28,
  "/assets/leadership/29.webp": leadership_29,
  "/assets/maldives-atolls-light.svg": maldives_atolls_light,
  "/assets/male-taxi-fleet.webp": male_taxi_fleet,
  "/assets/milestones/1981.webp": milestones_1981,
  "/assets/milestones/2003.webp": milestones_2003,
  "/assets/milestones/2008.webp": milestones_2008,
  "/assets/milestones/2015.webp": milestones_2015,
  "/assets/milestones/2019.webp": milestones_2019,
  "/assets/milestones/2020.webp": milestones_2020,
  "/assets/milestones/2024.webp": milestones_2024,
  "/assets/milestones/2025.webp": milestones_2025,
  "/assets/milestones/company-construction-and-dredging.webp": milestones_company_construction_and_dredging,
  "/assets/milestones/company1.webp": milestones_company1,
  "/assets/milestones/company2.webp": milestones_company2,
  "/assets/milestones/construction-and-dredging-public-transport.webp": milestones_construction_and_dredging_public_transport,
  "/assets/milestones/construction-and-dredging1.webp": milestones_construction_and_dredging1,
  "/assets/milestones/construction-and-dredging2.webp": milestones_construction_and_dredging2,
  "/assets/milestones/construction-and-dredging3.webp": milestones_construction_and_dredging3,
  "/assets/milestones/construction-and-dredging4.webp": milestones_construction_and_dredging4,
  "/assets/milestones/corporate-hero.webp": milestones_corporate_hero,
  "/assets/milestones/dredging.webp": milestones_dredging,
  "/assets/milestones/public-transport1.webp": milestones_public_transport1,
  "/assets/milestones/public-transport2.webp": milestones_public_transport2,
  "/assets/milestones/public-transport3.webp": milestones_public_transport3,
  "/assets/milestones/public-transport4.webp": milestones_public_transport4,
  "/assets/milestones/team-engineering.webp": milestones_team_engineering,
  "/assets/milestones/trading-and-engineering1.webp": milestones_trading_and_engineering1,
  "/assets/milestones/trading-and-engineering2.webp": milestones_trading_and_engineering2,
  "/assets/milestones/trading-and-engineering3.webp": milestones_trading_and_engineering3,
  "/assets/milestones/trading-and-engineering4.webp": milestones_trading_and_engineering4,
  "/assets/milestones/trading-and-engineering5.webp": milestones_trading_and_engineering5,
  "/assets/milestones/transport1.webp": milestones_transport1,
  "/assets/mission-scene.webp": mission_scene,
  "/assets/mtcc-logo.png": mtcc_logo,
  "/assets/mtcc-vendor-qr.svg": mtcc_vendor_qr,
  "/assets/mtcc-waves.svg": mtcc_waves,
  "/assets/product-image.webp": product_image,
  "/assets/section-photo.webp": section_photo,
  "/assets/shipbuilding.webp": shipbuilding,
  "/assets/team-engineering.webp": team_engineering,
  "/assets/team-welding.webp": team_welding,
  "/assets/transport.webp": transport,
  "/assets/vision-scene.webp": vision_scene,
};
